spring:
  application:
    name: backend
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/poker_project?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
